services:
  bot-pool-01:
    image: ${HUMMINGBOT_IMAGE:-ghcr.io/sawbay/hummingbot:custom}
    container_name: bot_1
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./bots/pools/bot_1/conf:/home/hummingbot/conf:rw
      - ./bots/pools/bot_1/data:/home/hummingbot/data:rw
      - ./bots/pools/bot_1/logs:/home/hummingbot/logs:rw
      - ./bots/scripts:/home/hummingbot/scripts:rw
      - ./bots/controllers:/home/hummingbot/controllers:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"
    tty: true
    stdin_open: true

  bot-pool-02:
    image: ${HUMMINGBOT_IMAGE:-ghcr.io/sawbay/hummingbot:custom}
    container_name: bot_2
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./bots/pools/bot_2/conf:/home/hummingbot/conf:rw
      - ./bots/pools/bot_2/data:/home/hummingbot/data:rw
      - ./bots/pools/bot_2/logs:/home/hummingbot/logs:rw
      - ./bots/scripts:/home/hummingbot/scripts:rw
      - ./bots/controllers:/home/hummingbot/controllers:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"
    tty: true
    stdin_open: true

  bot-pool-03:
    image: ${HUMMINGBOT_IMAGE:-ghcr.io/sawbay/hummingbot:custom}
    container_name: bot_3
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./bots/pools/bot_3/conf:/home/hummingbot/conf:rw
      - ./bots/pools/bot_3/data:/home/hummingbot/data:rw
      - ./bots/pools/bot_3/logs:/home/hummingbot/logs:rw
      - ./bots/scripts:/home/hummingbot/scripts:rw
      - ./bots/controllers:/home/hummingbot/controllers:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"
    tty: true
    stdin_open: true
