id: btc-short-grid
controller_name: grid_strike
controller_type: generic
activation_bounds: 0.001
connector_name: binance_perpetual_testnet
end_price: 76342.7
keep_position: false
leverage: 1
limit_price: 76724.41
max_open_orders: 15
max_orders_per_batch: 1
min_order_amount_quote: 10
min_spread_between_orders: 0.0001
order_frequency: 5
position_mode: ONEWAY
side: 2
start_price: 74824.3
total_amount_quote: 300
trading_pair: BTC-USDT
